name: "demo-action"
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8.x
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: install
        run: pnpm install
      - name: build
        run: pnpm build
  
          
